version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FORTAWESOME_TOKEN=${FORTAWESOME_TOKEN}
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pokedex
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pokedex
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
