version: '3.9'

services:
  app:
    environment:
      - DATABASE_URL="postgresql://postgres:WF3btJ11d5vTkO7QFdXB@containers-us-west-109.railway.app:7240/railway?connection_timeout=10&connection_limit=1"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FORTAWESOME_TOKEN=${FORTAWESOME_TOKEN} 
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pokedex
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pokedex
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  db-metrics:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: postgres://pokedex:secret@db:5432/pokedex?sslmode=disable
    ports:
      - 9187:9187
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - db-metrics

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3001:3000
    depends_on:
      - prometheus

volumes:
  postgres-data:
