import { Box, Heading, Text } from '@chakra-ui/react'
import FilterBar from '@components/filters/filter-bar'
import PokemonTypeFilter from '@components/filters/pokemon-type-filter'
import PokemonList from '@components/pokemon/pokemon-list'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        display="grid"
        p={[2, 4]}
        gap={[3, 5]}
        gridTemplateRows="repeat(3, auto) 1fr"
        // w="100%"
        h="100vh"
        // overflow="auto"
      >
        <Box>
          <Heading color="gray.700" size={['xl', '3xl']}>
            Pokédex
          </Heading>
          <Text fontSize={['md', 'lg']} color="gray.500">
            Search for a Pokémon by name or using its National Pokédex number.
          </Text>
        </Box>
        <FilterBar />
        <PokemonTypeFilter />
        <PokemonList />
      </Box>
    </div>
  )
}

export default Home
